language: "ko-KR"

knowledge_base:
    learnings:
        scope: auto
    file_patterns:
        - "docs/**"

reviews:
    profile: "chill"
    high_level_summary: true
    poem: false
    collapse_walkthrough: false
    sequence_diagrams: true
    suggested_labels: true
    auto_apply_labels: true

    path_filters:
        - "!**/*.lock"
        - "!**/build/**"
        - "!**/.gradle/**"
        - "!gradle/wrapper/**"
        - "!gradlew"
        - "!gradlew.bat"

    path_instructions:
        -   path: "**"
            instructions: |
                이 프로젝트는 Kotlin + Spring Boot 기반의 멀티모듈 프로젝트로, 헥사고날 아키텍처를 따릅니다.
                모듈 구성: zzan-core(공통), zzan-user, zzan-feed, zzan-liquor, zzan-place, zzan-infra, zzan-app
                각 모듈은 adapter(in/out), application(port/service), domain 레이어로 구성됩니다.
                - 비즈니스 로직은 domain 및 application/service 레이어에만 위치해야 합니다.
                - 외부 의존성(JPA, Redis 등)은 adapter/out 레이어에만 위치해야 합니다.
                - 모듈 간 직접 의존은 지양하고, zzan-infra의 어댑터를 통해 연결합니다.
                - 모듈 간 이벤트는 zzan-core의 event 패키지에 정의된 Spring Event로 통신합니다.

        -   path: "**/*Entity.kt"
            instructions: "연관관계 매핑(FetchType, cascade)과 소프트 딜리트(@SQLRestriction) 적용 여부를 확인하세요."

        -   path: "**/*JpaRepository.kt"
            instructions: "N+1 문제와 커서 페이지네이션 쿼리 조건을 확인하세요."

    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "[SKIP]"
        drafts: false
        base_branches:
            - "main"
            - "develop"

chat:
    auto_reply: true
